### ISSUE TITLE
Mängu tutvustav plakat

### ISSUE THREAD

**Issue by rmuld** [TLUHK-Portfolio/Mina-Tean#111]
- mängu nimi
- autorite nimed
- mängu põhiidee
- graafika näited
- tasemete näited

Plakati kriteeriumid:
- suurus A1
- pdf vormingus
- lõikevaru 3mm
- värviruum (cmyk ja fogra 39)

## Ressursid
- [Plakati juhend](https://github.com/tluhk/Multimeediumi_praktika/blob/master/docs/plakat.md)

**Comment by siiriinno** [comment]
[Plakat Mina Tean!.pdf](https://github.com/TLUHK-Portfolio/Mina-Tean/files/13474629/Plakat.Mina.Tean.pdf) @mrtrvl

**Comment by siiriinno** [comment]
[Plakat Mina Tean!.zip](https://github.com/TLUHK-Portfolio/Mina-Tean/files/13474643/Plakat.Mina.Tean.zip) @mrtrvl
